// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfdefense returns the embedded CollectionSpec for Bpfdefense.
func LoadBpfdefense() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfdefenseBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpfdefense: %w", err)
	}

	return spec, err
}

// LoadBpfdefenseObjects loads Bpfdefense and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfdefenseObjects
//	*BpfdefensePrograms
//	*BpfdefenseMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfdefenseObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfdefense()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfdefenseSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfdefenseSpecs struct {
	BpfdefenseProgramSpecs
	BpfdefenseMapSpecs
	BpfdefenseVariableSpecs
}

// BpfdefenseProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfdefenseProgramSpecs struct {
	TracepointBpfLoad *ebpf.ProgramSpec `ebpf:"tracepoint_bpf_load"`
}

// BpfdefenseMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfdefenseMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// BpfdefenseVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfdefenseVariableSpecs struct {
}

// BpfdefenseObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfdefenseObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfdefenseObjects struct {
	BpfdefensePrograms
	BpfdefenseMaps
	BpfdefenseVariables
}

func (o *BpfdefenseObjects) Close() error {
	return _BpfdefenseClose(
		&o.BpfdefensePrograms,
		&o.BpfdefenseMaps,
	)
}

// BpfdefenseMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfdefenseObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfdefenseMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *BpfdefenseMaps) Close() error {
	return _BpfdefenseClose(
		m.Events,
	)
}

// BpfdefenseVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfdefenseObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfdefenseVariables struct {
}

// BpfdefensePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfdefenseObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfdefensePrograms struct {
	TracepointBpfLoad *ebpf.Program `ebpf:"tracepoint_bpf_load"`
}

func (p *BpfdefensePrograms) Close() error {
	return _BpfdefenseClose(
		p.TracepointBpfLoad,
	)
}

func _BpfdefenseClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfdefense_bpfel.o
var _BpfdefenseBytes []byte
