// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCredAccess returns the embedded CollectionSpec for CredAccess.
func LoadCredAccess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CredAccessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CredAccess: %w", err)
	}

	return spec, err
}

// LoadCredAccessObjects loads CredAccess and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CredAccessObjects
//	*CredAccessPrograms
//	*CredAccessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCredAccessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCredAccess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CredAccessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredAccessSpecs struct {
	CredAccessProgramSpecs
	CredAccessMapSpecs
	CredAccessVariableSpecs
}

// CredAccessProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredAccessProgramSpecs struct {
	TpOpenat *ebpf.ProgramSpec `ebpf:"tp_openat"`
}

// CredAccessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredAccessMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// CredAccessVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredAccessVariableSpecs struct {
}

// CredAccessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCredAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredAccessObjects struct {
	CredAccessPrograms
	CredAccessMaps
	CredAccessVariables
}

func (o *CredAccessObjects) Close() error {
	return _CredAccessClose(
		&o.CredAccessPrograms,
		&o.CredAccessMaps,
	)
}

// CredAccessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCredAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredAccessMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *CredAccessMaps) Close() error {
	return _CredAccessClose(
		m.Events,
	)
}

// CredAccessVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCredAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredAccessVariables struct {
}

// CredAccessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCredAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredAccessPrograms struct {
	TpOpenat *ebpf.Program `ebpf:"tp_openat"`
}

func (p *CredAccessPrograms) Close() error {
	return _CredAccessClose(
		p.TpOpenat,
	)
}

func _CredAccessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed credaccess_bpfeb.o
var _CredAccessBytes []byte
