// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadExecTrace returns the embedded CollectionSpec for ExecTrace.
func LoadExecTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ExecTrace: %w", err)
	}

	return spec, err
}

// LoadExecTraceObjects loads ExecTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecTraceObjects
//	*ExecTracePrograms
//	*ExecTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecTraceSpecs struct {
	ExecTraceProgramSpecs
	ExecTraceMapSpecs
	ExecTraceVariableSpecs
}

// ExecTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecTraceProgramSpecs struct {
	TracepointExecve *ebpf.ProgramSpec `ebpf:"tracepoint_execve"`
}

// ExecTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecTraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ExecTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecTraceVariableSpecs struct {
}

// ExecTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecTraceObjects struct {
	ExecTracePrograms
	ExecTraceMaps
	ExecTraceVariables
}

func (o *ExecTraceObjects) Close() error {
	return _ExecTraceClose(
		&o.ExecTracePrograms,
		&o.ExecTraceMaps,
	)
}

// ExecTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecTraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ExecTraceMaps) Close() error {
	return _ExecTraceClose(
		m.Events,
	)
}

// ExecTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecTraceVariables struct {
}

// ExecTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecTracePrograms struct {
	TracepointExecve *ebpf.Program `ebpf:"tracepoint_execve"`
}

func (p *ExecTracePrograms) Close() error {
	return _ExecTraceClose(
		p.TracepointExecve,
	)
}

func _ExecTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exectrace_bpfel.o
var _ExecTraceBytes []byte
