// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadMemoryAnomaly returns the embedded CollectionSpec for MemoryAnomaly.
func LoadMemoryAnomaly() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemoryAnomalyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load MemoryAnomaly: %w", err)
	}

	return spec, err
}

// LoadMemoryAnomalyObjects loads MemoryAnomaly and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemoryAnomalyObjects
//	*MemoryAnomalyPrograms
//	*MemoryAnomalyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemoryAnomalyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMemoryAnomaly()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemoryAnomalySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryAnomalySpecs struct {
	MemoryAnomalyProgramSpecs
	MemoryAnomalyMapSpecs
	MemoryAnomalyVariableSpecs
}

// MemoryAnomalyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryAnomalyProgramSpecs struct {
	TracepointMmap     *ebpf.ProgramSpec `ebpf:"tracepoint_mmap"`
	TracepointMprotect *ebpf.ProgramSpec `ebpf:"tracepoint_mprotect"`
}

// MemoryAnomalyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryAnomalyMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// MemoryAnomalyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryAnomalyVariableSpecs struct {
}

// MemoryAnomalyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryAnomalyObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryAnomalyObjects struct {
	MemoryAnomalyPrograms
	MemoryAnomalyMaps
	MemoryAnomalyVariables
}

func (o *MemoryAnomalyObjects) Close() error {
	return _MemoryAnomalyClose(
		&o.MemoryAnomalyPrograms,
		&o.MemoryAnomalyMaps,
	)
}

// MemoryAnomalyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryAnomalyObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryAnomalyMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *MemoryAnomalyMaps) Close() error {
	return _MemoryAnomalyClose(
		m.Events,
	)
}

// MemoryAnomalyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryAnomalyObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryAnomalyVariables struct {
}

// MemoryAnomalyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryAnomalyObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryAnomalyPrograms struct {
	TracepointMmap     *ebpf.Program `ebpf:"tracepoint_mmap"`
	TracepointMprotect *ebpf.Program `ebpf:"tracepoint_mprotect"`
}

func (p *MemoryAnomalyPrograms) Close() error {
	return _MemoryAnomalyClose(
		p.TracepointMmap,
		p.TracepointMprotect,
	)
}

func _MemoryAnomalyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memoryanomaly_bpfeb.o
var _MemoryAnomalyBytes []byte
