// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadModuleLoad returns the embedded CollectionSpec for ModuleLoad.
func LoadModuleLoad() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ModuleLoadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ModuleLoad: %w", err)
	}

	return spec, err
}

// LoadModuleLoadObjects loads ModuleLoad and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ModuleLoadObjects
//	*ModuleLoadPrograms
//	*ModuleLoadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadModuleLoadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadModuleLoad()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ModuleLoadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleLoadSpecs struct {
	ModuleLoadProgramSpecs
	ModuleLoadMapSpecs
	ModuleLoadVariableSpecs
}

// ModuleLoadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleLoadProgramSpecs struct {
	KprobeDoInitModule *ebpf.ProgramSpec `ebpf:"kprobe_do_init_module"`
}

// ModuleLoadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleLoadMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ModuleLoadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleLoadVariableSpecs struct {
}

// ModuleLoadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadModuleLoadObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleLoadObjects struct {
	ModuleLoadPrograms
	ModuleLoadMaps
	ModuleLoadVariables
}

func (o *ModuleLoadObjects) Close() error {
	return _ModuleLoadClose(
		&o.ModuleLoadPrograms,
		&o.ModuleLoadMaps,
	)
}

// ModuleLoadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadModuleLoadObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleLoadMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ModuleLoadMaps) Close() error {
	return _ModuleLoadClose(
		m.Events,
	)
}

// ModuleLoadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadModuleLoadObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleLoadVariables struct {
}

// ModuleLoadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadModuleLoadObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleLoadPrograms struct {
	KprobeDoInitModule *ebpf.Program `ebpf:"kprobe_do_init_module"`
}

func (p *ModuleLoadPrograms) Close() error {
	return _ModuleLoadClose(
		p.KprobeDoInitModule,
	)
}

func _ModuleLoadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed moduleload_bpfel.o
var _ModuleLoadBytes []byte
