// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNetConnect returns the embedded CollectionSpec for NetConnect.
func LoadNetConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetConnect: %w", err)
	}

	return spec, err
}

// LoadNetConnectObjects loads NetConnect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetConnectObjects
//	*NetConnectPrograms
//	*NetConnectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetConnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetConnectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetConnectSpecs struct {
	NetConnectProgramSpecs
	NetConnectMapSpecs
	NetConnectVariableSpecs
}

// NetConnectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetConnectProgramSpecs struct {
	TracepointConnect *ebpf.ProgramSpec `ebpf:"tracepoint_connect"`
}

// NetConnectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetConnectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// NetConnectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetConnectVariableSpecs struct {
}

// NetConnectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetConnectObjects struct {
	NetConnectPrograms
	NetConnectMaps
	NetConnectVariables
}

func (o *NetConnectObjects) Close() error {
	return _NetConnectClose(
		&o.NetConnectPrograms,
		&o.NetConnectMaps,
	)
}

// NetConnectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetConnectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *NetConnectMaps) Close() error {
	return _NetConnectClose(
		m.Events,
	)
}

// NetConnectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetConnectVariables struct {
}

// NetConnectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetConnectPrograms struct {
	TracepointConnect *ebpf.Program `ebpf:"tracepoint_connect"`
}

func (p *NetConnectPrograms) Close() error {
	return _NetConnectClose(
		p.TracepointConnect,
	)
}

func _NetConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netconnect_bpfel.o
var _NetConnectBytes []byte
