// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadPrivesc returns the embedded CollectionSpec for Privesc.
func LoadPrivesc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PrivescBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Privesc: %w", err)
	}

	return spec, err
}

// LoadPrivescObjects loads Privesc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PrivescObjects
//	*PrivescPrograms
//	*PrivescMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPrivescObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPrivesc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PrivescSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivescSpecs struct {
	PrivescProgramSpecs
	PrivescMapSpecs
	PrivescVariableSpecs
}

// PrivescProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivescProgramSpecs struct {
	KprobeCommitCreds *ebpf.ProgramSpec `ebpf:"kprobe_commit_creds"`
}

// PrivescMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivescMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// PrivescVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivescVariableSpecs struct {
}

// PrivescObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPrivescObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivescObjects struct {
	PrivescPrograms
	PrivescMaps
	PrivescVariables
}

func (o *PrivescObjects) Close() error {
	return _PrivescClose(
		&o.PrivescPrograms,
		&o.PrivescMaps,
	)
}

// PrivescMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPrivescObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivescMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *PrivescMaps) Close() error {
	return _PrivescClose(
		m.Events,
	)
}

// PrivescVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPrivescObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivescVariables struct {
}

// PrivescPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPrivescObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivescPrograms struct {
	KprobeCommitCreds *ebpf.Program `ebpf:"kprobe_commit_creds"`
}

func (p *PrivescPrograms) Close() error {
	return _PrivescClose(
		p.KprobeCommitCreds,
	)
}

func _PrivescClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed privesc_bpfeb.o
var _PrivescBytes []byte
