// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadReverseShell returns the embedded CollectionSpec for ReverseShell.
func LoadReverseShell() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ReverseShellBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ReverseShell: %w", err)
	}

	return spec, err
}

// LoadReverseShellObjects loads ReverseShell and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ReverseShellObjects
//	*ReverseShellPrograms
//	*ReverseShellMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadReverseShellObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadReverseShell()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ReverseShellSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ReverseShellSpecs struct {
	ReverseShellProgramSpecs
	ReverseShellMapSpecs
	ReverseShellVariableSpecs
}

// ReverseShellProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ReverseShellProgramSpecs struct {
	TpEnterDup2  *ebpf.ProgramSpec `ebpf:"tp_enter_dup2"`
	TpEnterDup3  *ebpf.ProgramSpec `ebpf:"tp_enter_dup3"`
	TpExecRshell *ebpf.ProgramSpec `ebpf:"tp_exec_rshell"`
	TpExitSocket *ebpf.ProgramSpec `ebpf:"tp_exit_socket"`
}

// ReverseShellMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ReverseShellMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	PendingRshell *ebpf.MapSpec `ebpf:"pending_rshell"`
	SocketFds     *ebpf.MapSpec `ebpf:"socket_fds"`
}

// ReverseShellVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ReverseShellVariableSpecs struct {
}

// ReverseShellObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadReverseShellObjects or ebpf.CollectionSpec.LoadAndAssign.
type ReverseShellObjects struct {
	ReverseShellPrograms
	ReverseShellMaps
	ReverseShellVariables
}

func (o *ReverseShellObjects) Close() error {
	return _ReverseShellClose(
		&o.ReverseShellPrograms,
		&o.ReverseShellMaps,
	)
}

// ReverseShellMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadReverseShellObjects or ebpf.CollectionSpec.LoadAndAssign.
type ReverseShellMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	PendingRshell *ebpf.Map `ebpf:"pending_rshell"`
	SocketFds     *ebpf.Map `ebpf:"socket_fds"`
}

func (m *ReverseShellMaps) Close() error {
	return _ReverseShellClose(
		m.Events,
		m.PendingRshell,
		m.SocketFds,
	)
}

// ReverseShellVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadReverseShellObjects or ebpf.CollectionSpec.LoadAndAssign.
type ReverseShellVariables struct {
}

// ReverseShellPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadReverseShellObjects or ebpf.CollectionSpec.LoadAndAssign.
type ReverseShellPrograms struct {
	TpEnterDup2  *ebpf.Program `ebpf:"tp_enter_dup2"`
	TpEnterDup3  *ebpf.Program `ebpf:"tp_enter_dup3"`
	TpExecRshell *ebpf.Program `ebpf:"tp_exec_rshell"`
	TpExitSocket *ebpf.Program `ebpf:"tp_exit_socket"`
}

func (p *ReverseShellPrograms) Close() error {
	return _ReverseShellClose(
		p.TpEnterDup2,
		p.TpEnterDup3,
		p.TpExecRshell,
		p.TpExitSocket,
	)
}

func _ReverseShellClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed reverseshell_bpfeb.o
var _ReverseShellBytes []byte
